# Generated by Django 2.1.4 on 2020-03-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewriter',
            name='image',
            field=models.FileField(upload_to='post_images'),
        ),
    ]
