# Generated by Django 2.1.4 on 2020-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_imagewriter_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewriter',
            name='font',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
