# Generated by Django 2.1.4 on 2020-04-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0006_imagewriter_multirefiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagewriter',
            name='multirefiles',
        ),
    ]
