# Generated by Django 2.1.4 on 2020-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0008_excelfilestore'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewriter',
            name='pictype',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
