# Generated by Django 2.1.4 on 2020-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFIleShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multirefiles', models.FileField(upload_to='schedule')),
            ],
        ),
    ]
