# Generated by Django 2.1.4 on 2020-04-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpressrest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleniumimagestore',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seleniumimagestore',
            name='title',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seleniumimagestore',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
