# Generated by Django 2.1.4 on 2020-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimagesstore',
            name='image',
            field=models.ImageField(upload_to='livestreams/images'),
        ),
    ]
