# Generated by Django 2.1.4 on 2020-04-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livedash', '0003_auto_20200420_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfilestore',
            name='data',
        ),
    ]
