# Generated by Django 2.1.4 on 2020-04-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livedash', '0004_remove_excelfilestore_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfilestore',
            name='excel',
        ),
        migrations.AddField(
            model_name='excelfilestore',
            name='data',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
    ]
